spring.application.name: VaultyAuth
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/**.xml
  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
jwt:
  private.key: ${PRIVATE_KEY}
  public.key: ${PUBLIC_KEY}