spring.application.name: VaultyAuth
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/**.xml
jwt:
  private.key: classpath:/private_key.pem
  public.key: classpath:/public.pub
password.key: classpath:/password_key.pem