name: build-and-deploy.yml
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Jar file
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Give gradle permissions
        run: chmod +x gradlew

      - name: Create key files
        run: |
          echo ${{ secrets.PRIVATE_KEY }} > src/main/resources/private_key.pem
          echo ${{ secrets.PUBLIC_KEY }} > src/main/resources/public.pub

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: kush-banbah/togo:latest
          secrets: |
            "DB_URL"=${{ secrets.DB_URL}}"
            "DB_PASSWORD"=${{ secrets.DB_PASSWORD}}}"
            "DB_USERNAME"=${{ secrets.DB_USERNAME}}"
